# Generated by Django 4.2.2 on 2023-07-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_productversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
