# Generated by Django 4.2.2 on 2023-07-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productversion_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=1800, verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за ед. продукта'),
        ),
        migrations.AlterField(
            model_name='productversion',
            name='description',
            field=models.TextField(max_length=1800, verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='productversion',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='productversion',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за ед. продукта'),
        ),
    ]
