# Generated by Django 4.2.2 on 2023-07-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productversion',
            name='versions',
            field=models.IntegerField(default=0),
        ),
    ]
