# Generated by Django 4.2.2 on 2023-07-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_productversion_versions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productversion',
            name='versions',
            field=models.CharField(default=''),
        ),
    ]
